import type { Metadata } from 'next';
import "./globals.css";
import Header from "../components/header";
import { Inter, Cormorant_Unicase, Martel_Sans } from "next/font/google";



const inter = Martel_Sans({
  subsets: ["latin"],
  weight: "200",
  style: ["normal"],
});
export const metadata: Metadata = {
  title: 'db agricultura',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="overflow-x-auto">
      <head>
        <link rel="icon" href="/images/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <Header />
        <div
          style={{
            minHeight: "100vh",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
